// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.jsx";
import * as $1 from "./routes/_middleware.js";
import * as $2 from "./routes/about.jsx";
import * as $3 from "./routes/entities.jsx";
import * as $4 from "./routes/entity.jsx";
import * as $5 from "./routes/index.jsx";
import * as $6 from "./routes/print/[vexillologist]/[vexillographer]/[variant]/[instance]/[code].jsx";
import * as $7 from "./routes/tools.jsx";
import * as $8 from "./routes/tools/svgd-transpiler.jsx";
import * as $9 from "./routes/tools/threevex.jsx";
import * as $10 from "./routes/tools/zigzagger.jsx";
import * as $11 from "./routes/vexillologists/[vexillologist].jsx";
import * as $12 from "./routes/vexillologists/[vexillologist]/[vexillographer].jsx";
import * as $13 from "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant].jsx";
import * as $14 from "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant]/[instance].jsx";
import * as $15 from "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant]/[instance]/[code].jsx";
import * as $16 from "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant]/[instance]/[code]/[file].js";
import * as $$0 from "./islands/instances-list-item.jsx";
import * as $$1 from "./islands/mobile-menu.jsx";
import * as $$2 from "./islands/random-flag.jsx";
import * as $$3 from "./islands/svgd-transpiler.jsx";
import * as $$4 from "./islands/threevex.jsx";
import * as $$5 from "./islands/zigzagger.jsx";

const manifest = {
  routes: {
    "./routes/_app.jsx": $0,
    "./routes/_middleware.js": $1,
    "./routes/about.jsx": $2,
    "./routes/entities.jsx": $3,
    "./routes/entity.jsx": $4,
    "./routes/index.jsx": $5,
    "./routes/print/[vexillologist]/[vexillographer]/[variant]/[instance]/[code].jsx":
      $6,
    "./routes/tools.jsx": $7,
    "./routes/tools/svgd-transpiler.jsx": $8,
    "./routes/tools/threevex.jsx": $9,
    "./routes/tools/zigzagger.jsx": $10,
    "./routes/vexillologists/[vexillologist].jsx": $11,
    "./routes/vexillologists/[vexillologist]/[vexillographer].jsx": $12,
    "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant].jsx":
      $13,
    "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant]/[instance].jsx":
      $14,
    "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant]/[instance]/[code].jsx":
      $15,
    "./routes/vexillologists/[vexillologist]/[vexillographer]/[variant]/[instance]/[code]/[file].js":
      $16,
  },
  islands: {
    "./islands/instances-list-item.jsx": $$0,
    "./islands/mobile-menu.jsx": $$1,
    "./islands/random-flag.jsx": $$2,
    "./islands/svgd-transpiler.jsx": $$3,
    "./islands/threevex.jsx": $$4,
    "./islands/zigzagger.jsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
