// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.jsx";
import * as $1 from "./routes/about.jsx";
import * as $2 from "./routes/entities.jsx";
import * as $3 from "./routes/entity.jsx";
import * as $4 from "./routes/flag.jsx";
import * as $5 from "./routes/index.jsx";
import * as $6 from "./routes/tools.jsx";
import * as $7 from "./routes/tools/zigzagger.jsx";
import * as $$0 from "./islands/instances-list-item.jsx";
import * as $$1 from "./islands/mobile-menu.jsx";
import * as $$2 from "./islands/random-flag.jsx";
import * as $$3 from "./islands/zigzagger.jsx";

const manifest = {
  routes: {
    "./routes/_app.jsx": $0,
    "./routes/about.jsx": $1,
    "./routes/entities.jsx": $2,
    "./routes/entity.jsx": $3,
    "./routes/flag.jsx": $4,
    "./routes/index.jsx": $5,
    "./routes/tools.jsx": $6,
    "./routes/tools/zigzagger.jsx": $7,
  },
  islands: {
    "./islands/instances-list-item.jsx": $$0,
    "./islands/mobile-menu.jsx": $$1,
    "./islands/random-flag.jsx": $$2,
    "./islands/zigzagger.jsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
